using Svelto.ECS.Example.Survive.Camera;
using Svelto.ECS.Example.Survive.Enemies;
using Svelto.ECS.Example.Survive.Sound;

namespace Svelto.ECS.Example.Survive.Player
{
	//defines the EntityViewStructs and EntityStructs generated by the creation
	//of the Player Entity
	public class PlayerEntityDescriptor : GenericEntityDescriptor<PlayerEntityView,
		EnemyTargetEntityViewStruct, DamageSoundEntityView, CameraTargetEntityView, HealthEntityStruct, PlayerInputDataStruct>
	{}
}
